@startuml State_Machine_Canonical_States

' --- ENGINE SETUP & FORMATING ---
skinparam linetype splines
skinparam nodesep 120
skinparam ranksep 120
skinparam dpi 300
skinparam shadowing true

skinparam state {
    BorderRadius 8
    Padding 12
    Margin 10
}

title Máquina de Estados Canónicos: AstroGit-OS Site Master

' --- GLOBAL CONTAINER ---
state "Active" as SYSTEM_ACTIVE {
    
    state "Idle" as IDLE    
    ' --- SUBESTADO COMPUESTO OPERACIONAL ---
    state "Operational" as OPERATIONAL {
        state In_Preparation
        state Standby
        state In_Observation
        
        In_Preparation -right-> Standby : Configuration
        Standby -right-> In_Observation : Start_Science
        In_Observation -left-> Standby : Pause_Science
        Standby -left-> In_Preparation : Reconfigure
    }
    
    ' --- INTERNAL TRANSITIONS ---
    IDLE -down-> In_Preparation : Starup
    Standby -up-> IDLE : Park
}

' --- SERVICE & MAINTENANCE STATES ---
state Safe_Mode
state In_Maintenance

' --- EXTREME EXTERNAL EVENTS ---
SYSTEM_ACTIVE --> Safe_Mode : extreme_external_event

' --- SAFE_MODE RECOVERY ---
Safe_Mode --> In_Maintenance : Manual_Verification
Safe_Mode --> In_Preparation : Safety OK
Safe_Mode --> IDLE : Reset

' --- FROM/TO: MAINTENANCE ---
OPERATIONAL --> In_Maintenance : System_Fault
In_Preparation --> In_Maintenance : Conditioning_Failure
In_Maintenance --> Standby : Maintenance_Complete

@enduml