@startuml "Telescope_State_Machine"
skinparam monochrome true
skinparam shadowing false
skinparam packageStyle rectangle

title Máquina de Estados de Telescopio Terrestre Clase 30m

[*] --> En_Reposo : Apagado General

state "En Energía / Operativo" as OPERATIVO {
    
    --
    [*] --> En_Preparacion
    En_Preparacion --> En_Espera : Calibración OK
    
    En_Espera --> En_Observacion : Iniciar Ciencia
    En_Observacion --> En_Espera : Pausar Ciencia
    
    En_Espera --> En_Mantenimiento : Intervención Técnica
    En_Mantenimiento --> En_Espera : Fin Mantenimiento
    
    En_Preparacion --> En_Mantenimiento : Falla en Acondicionamiento
    
    --
    [*] --> Nominal
    Nominal --> En_Resguardo : [Alerta Clima / Sismo]
    En_Resguardo --> Nominal : [Condiciones Seguras]
    
}

OPERATIVO --> En_Reposo : Apagado Seguro / Parqueo

@endum
